# Hello There!!!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johnsong Construction
email: (((N/A)))
description: > # this means to ignore newlines until "baseurl:"
  We build log homes for you and your family. Best log homes around! Located at 23897 Grey Fox Ln, in Grantsburg, WI, 54840.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb 
github_username:  jekyll

# Build settings
markdown: kramdown
